apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-mouhamed-salane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mmouhameeed/gitops-mouhamed-salane.git
    targetRevision: main
    path: chart-mouhamed-salane
  destination:
    server: https://kubernetes.default.svc
    namespace: mouhamed-salane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
