replicaCount: 3

image:
  repository: ghcr.io/mmouhameeed/gitops-mouhamed-salane
  tag: latest
  pullPolicy: Always

studentName: "Mouhamed-Salane"
appVersion: "v1.0.0"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

namespace: mouhamed-salane

ingress:
  enabled: true
  host: mouhamed-salane.local
